version: '3.4'

services:
  db:
    image: "mysql/mysql-server:latest"
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "db_data:/var/lib/mysql"
  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_HOST: "${DB_PASSWORD}"
    depends_on:
      - db
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
    driver: local